### ISSUE TITLE
There is NoMethodError `encode': undefined method `force_encoding' while running through terminal

### ISSUE THREAD

**Issue by CuriousNikhil** [Widdershin/sonic-pi-cli#18]
/var/lib/gems/1.8/gems/osc-ruby-1.1.1/lib/osc-ruby/osc_types.rb:21:in `encode': undefined method `force_encoding' for "/run-code\000\000\000":String (NoMethodError)
	from /var/lib/gems/1.8/gems/osc-ruby-1.1.1/lib/osc-ruby/message.rb:31:in `encode'
	from /var/lib/gems/1.8/gems/osc-ruby-1.1.1/lib/osc-ruby/client.rb:10:in `send'
	from /var/lib/gems/1.8/gems/sonic-pi-cli-0.1.1/lib/sonic_pi.rb:39:in `send_command'
	from /var/lib/gems/1.8/gems/sonic-pi-cli-0.1.1/lib/sonic_pi.rb:14:in `run'
	from /var/lib/gems/1.8/gems/sonic-pi-cli-0.1.1/bin/sonic_pi:58:in `run'
	from /var/lib/gems/1.8/gems/sonic-pi-cli-0.1.1/bin/sonic_pi:62
	from /usr/local/bin/sonic_pi:23:in `load'
	from /usr/local/bin/sonic_pi:23

**Comment by rbnpi** [comment]
I think this is an error from Sonic Pi because you used run-code instead of run_code (See the syntax in the Help File Lang section for Sonic Pi

**Comment by CuriousNikhil** [comment]
No sir. I'm just using sonic-pi-cli and i am just placing this command `sonic_pi play 50` in the terminal. My terminal window is showing the above error.

**Comment by rbnpi** [comment]
OK. What platform are you running on? what version of Sonic Pi?

**Comment by CuriousNikhil** [comment]
I am running sonic-pi on RaspberryPi with latest version of `2.10` 
the output of `gem-list` is:
```
*** LOCAL GEMS ***

osc-ruby (1.1.1)
sonic-pi-cli (0.1.1)
```
I recently brought a raspi board so it's with latest installed versions of ruby and all.

**Comment by Widdershin** [comment]
Am I right in thinking that you're running a relatively old version of Ruby (1.8)? Would you be able to try again with a newer version?
